// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:save_track/features/dashboard/dashboard_models.dart';
import 'package:save_track/features/goals/goal_models.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CreateGoalDtoAdapter());
    registerAdapter(DashboardDataAdapter());
    registerAdapter(GoalAdapter());
    registerAdapter(TransactionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CreateGoalDtoAdapter());
    registerAdapter(DashboardDataAdapter());
    registerAdapter(GoalAdapter());
    registerAdapter(TransactionAdapter());
  }
}
